# Generated by Django 3.2.15 on 2022-08-13 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_emailverifyotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordOtp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forgot_password_otp',
            },
        ),
    ]
