# Generated by Django 3.2.15 on 2022-08-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multi_image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
